# Generated by Django 5.2.6 on 2025-09-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True, verbose_name='Name')),
                ('type', models.CharField(blank=True, choices=[('fire', 'Fire'), ('water', 'Water'), ('grass', 'Grass'), ('electric', 'Electric'), ('normal', 'Normal'), ('rock', 'Rock')], null=True, verbose_name='Type')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='Level')),
                ('hp', models.IntegerField(blank=True, null=True, verbose_name='HP')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pokemons/', verbose_name='Image')),
            ],
        ),
    ]
