# Generated by Django 5.2.8 on 2025-11-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wage_donalds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meals/'),
        ),
    ]
