# Generated by Django 5.2.8 on 2025-11-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wage_donalds', '0002_meal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='is_vegan',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
