# Generated by Django 5.2.7 on 2025-10-08 09:50

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('milk_type', models.CharField(choices=[('COW', 'Cow'), ('SHEEP', 'Sheep'), ('GOAT', 'Goat'), ('BUFFALO', 'Buffalo'), ('OTHER', 'Other')], max_length=10)),
                ('expiration_date', models.DateField(help_text='Expiration date (best before)')),
                ('price_eur_per_kg', models.DecimalField(decimal_places=2, max_digits=7)),
                ('country_of_origin', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
