# Generated by Django 5.2.7 on 2025-10-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheese',
            name='milk_type',
            field=models.CharField(max_length=10),
        ),
    ]
